#!/bin/sh
rm -rf tmp
cp -r pkg tmp
# sed -i -e 's/DEBUG = True/DEBUG = False/g' tmp/settings.py
rsync -avz -e "ssh -i iphemap" tmp/ root@158.69.167.226:/home/iphemap/pkg
rsync -avz -e "ssh -i iphemap" static/ root@158.69.167.226:/home/iphemap/static
rm -rf tmp
