# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipscdb', '0008_auto_20150303_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
