# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipscdb', '0012_auto_20160111_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='geoid_link',
        ),
        migrations.RemoveField(
            model_name='study',
            name='platform_geoid_link',
        ),
    ]
