# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipscdb', '0013_auto_20160112_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='geoid',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='study',
            name='platform_geo_id',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AlterField(
            model_name='study',
            name='platform_name',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
